development:
  bucket: "KoalaWear"
  access_key_id: "AKIAJG673TJKBRKYG2ZA"
  secret_access_key: "ARsvXTi4JBdgKvB2xxXxyynUlFqd2iHvFrHhFWjR"

test:
  bucket: "KoalaWear"
  access_key_id: "AKIAJG673TJKBRKYG2ZA"
  secret_access_key: "ARsvXTi4JBdgKvB2xxXxyynUlFqd2iHvFrHhFWjR"

production:
  bucket: "KoalaWear"
  access_key_id: "AKIAJG673TJKBRKYG2ZA"
  secret_access_key: "ARsvXTi4JBdgKvB2xxXxyynUlFqd2iHvFrHhFWjR"